VOID_TYPE = {
    "VoidT1": "Lith",
    "VoidT2": "Meso",
    "VoidT3": "Neo",
    "VoidT4": "Axi",
    "VoidT5": "Requiem",
    "VoidT6": "Omnia",
}

FACTION_TYPE = {
    "FC_GRINEER": "Grineer",
    "FC_CORPUS": "Corpus",
    "FC_OROKIN": "Orokin",
    "FC_INFESTATION": "Infestation",
    "FC_MITW": "The Murmur",
    "FC_SCALDRA": "Scaldra",
    "FC_TECHROT": "Techrot",
}

MISSION_TYPE = {
    "MT_ALCHEMY": "Alchemy",
    "MT_ARENA": "Arena",
    "MT_ARMAGEDDON": "Void Armageddon",
    "MT_ARTIFACT": "Disruption",
    "MT_ASCENSION": "Ascension",
    "MT_ASSAULT": "Assault",
    "MT_CORRUPTION": "Void Flood",
    "MT_DESCENT": "The Descendia",
    "MT_ENDLESS_CAPTURE": "Legacyte Harvest",
    "MT_ENDLESS_DUVIRI": "The Circuit",
    "MT_ENDLESS_EXTERMINATION": "Sanctuary Onslaught",
    "MT_EVACUATION": "Defection",
    "MT_EXCAVATE": "Excavation",
    "MT_GENERIC": "MT_GENERIC",
    "MT_HIVE": "Hive Sabotage",
    "MT_JUNCTION": "Solar Rail Junction",
    "MT_LANDSCAPE": "Free Roam",
    "MT_MASTERY": "Mastery Test",
    "MT_OFFERING": "Shrine Defense",
    "MT_PURGE": "MT_PURGE",
    "MT_PURIFY": "Infested Salvage",
    "MT_PURSUIT": "Pursuit",
    "MT_PVP": "Conclave",
    "MT_PVPVE": "Faceoff",
    "MT_RACE": "Rush (Archwing)",
    "MT_RAID": "Trial",
    "MT_RAILJACK": "Railjack",
    "MT_RECOVERY": "Recovery",
    "MT_RESOURCE_THEFT": "MT_RESOURCE_THEFT",
    "MT_RETRIEVAL": "Hijack",
    "MT_SALVAGE": "Solar Rail Conflict",
    "MT_TAU_WAR": "The Perita Rebellion",
    "MT_TERRITORY": "Interception",
    "MT_VAULTS": "Netracells",
    "MT_VOID_CASCADE": "Void Cascade",
    "MT_ASSASSINATION": "Assassination",
    "MT_CAPTURE": "Capture",
    "MT_COUNTER_INTEL": "Deception",
    "MT_DEFENSE": "Defense",
    "MT_EXTERMINATION": "Extermination",
    "MT_INTEL": "Spy",
    "MT_MOBILE_DEFENSE": "Mobile Defense",
    "MT_RESCUE": "Rescue",
    "MT_SABOTAGE": "Sabotage",
    "MT_SURVIVAL": "Survival",
}

# Skeptical mappings from what I'm seeing in game and worldstate
ARCHIMEDEA_DIFFICULTIES = {
    "AcceleratedEnemies": {"name": "Bold Venture", "description": "Enemies deal -15% damage and take 15% damage, but gain 15% movement speed, attack speed and fire rate."},
    "ArtilleryBeacons": {"name": "Artillery Beacons", "description": "When killed, Scaldra troops drop beacons that summon bombardments."},
    "BalloonFest": {"name": "Balloonfest", "description": "Scaldra Harbingers are more numerous and attack and move more quickly."},
    "DoubleTroubleLegacyte": {"name": "Mitosis", "description": "2 Legacytes spawn each round. Twice as many captures are needed for success."},
    "DrainingResiduals": {"name": "Devil's Bargain", "description": "Allies within 4m of slain enemies gain 25% fire rate at the cost of -50% ammo efficiency."},
    "EfervonFog": {"name": "Dense Fog", "description": "Efervon gas blankets the level. Enemies drop filters that can provide a temporary reprive."},
    "EMPBlackHole": {"name": "Alluring Arcocanids", "description": "As Rogue Arcocanids charge attacks, they pull warframes towards them."},
    "ExplosiveCrawlers": {"name": "Explosive Potential", "description": "Rupturing Fragments replace Shuffling Fragments."},
    "ExplosiveEnergy": {"name": "Miasmite Mash", "description": "Enemies drop Miasmite upon death that immediately rush Flare."},
    "FactionSwarm_Scaldra": {"name": "Scaldra Speed Run", "description": "All enemies are replaced with Scaldra and move faster."},
    "HostileSecurity": {"name": "Eroding Senses", "description": "Auricle and Vitreum take damage over time. Collecting the required glyphs will halt the DoT and partially heal them."},
    "NecramechActivation": {"name": "Necramech Influx", "description": "Necramechs appear with greater frequency."},
    "Quicksand": {"name": "Entanglement", "description": "Allies within 4m of slain enemies endure reduced movement and parkour velocity."},
    "ShieldedFoes": {"name": "Bolstered Belligerents", "description": "All enemies have 50% overguard equal to 50% of their max health."},
    "StickyFingers": {"name": "Engorged Gruzzlings", "description": "All Gruzzlings are Eximus."},
    "TankReinforcements": {"name": "Reinforcements", "description": "Reinforcements will arrive during the fight; first Scaldra, then Techrot."},
    "VoidAberration": {"name": "Vampyric Liminus", "description": "Immortal Duviri Liminus that drains health and energy when close."},

}

# Skeptical mappings from what I'm seeing in game and worldstate
ARCHIMEDEA_VARIABLES = {
    "AbilityLockout": {"name": "Powerless", "description": "All abilities are disabled until squad kills 50 enemies."},
    "Armorless": {"name": "Fractured Armor", "description": "Casting an ability reduced armor by 10% for 10s."},
    "DullBlades": {"name": "Dull Blades", "description": "-50% combo count chance."},
    "EnergyStarved": {"name": "Constricted", "description": "Max energy reduced by 50%."},
    "Knifestep": {"name": "Knifestep Syndrome", "description": "Lose 2 health when moving. Jumping pauses the effect."},
    "ShieldDelay": {"name": "Lethargic Shields", "description": "Shield recharge delay increased by 500%."},
    "Starvation": {"name": "Ammo Deficit", "description": "Ammo restored by drops and gear redcued by 75%."},
}
