VOID_TYPE = {
    "VoidT1": "Lith",
    "VoidT2": "Meso",
    "VoidT3": "Neo",
    "VoidT4": "Axi",
    "VoidT5": "Requiem",
    "VoidT6": "Omnia",
}

FACTION_TYPE = {
    "FC_GRINEER": "Grineer",
    "FC_CORPUS": "Corpus",
    "FC_OROKIN": "Orokin",
    "FC_INFESTATION": "Infestation",
    "FC_MITW": "The Murmur",
    "FC_SCALDRA": "Scaldra",
    "FC_TECHROT": "Techrot",
}

MISSION_TYPE = {
    "MT_ALCHEMY": "Alchemy",
    "MT_ARENA": "Arena",
    "MT_ARMAGEDDON": "Void Armageddon",
    "MT_ARTIFACT": "Disruption",
    "MT_ASCENSION": "Ascension",
    "MT_ASSAULT": "Assault",
    "MT_CORRUPTION": "Void Flood",
    "MT_DESCENT": "The Descendia",
    "MT_ENDLESS_CAPTURE": "Legacyte Harvest",
    "MT_ENDLESS_DUVIRI": "The Circuit",
    "MT_ENDLESS_EXTERMINATION": "Sanctuary Onslaught",
    "MT_EVACUATION": "Defection",
    "MT_EXCAVATE": "Excavation",
    "MT_GENERIC": "MT_GENERIC",
    "MT_HIVE": "Hive Sabotage",
    "MT_JUNCTION": "Solar Rail Junction",
    "MT_LANDSCAPE": "Free Roam",
    "MT_MASTERY": "Mastery Test",
    "MT_OFFERING": "Shrine Defense",
    "MT_PURGE": "MT_PURGE",
    "MT_PURIFY": "Infested Salvage",
    "MT_PURSUIT": "Pursuit",
    "MT_PVP": "Conclave",
    "MT_PVPVE": "Faceoff",
    "MT_RACE": "Rush (Archwing)",
    "MT_RAID": "Trial",
    "MT_RAILJACK": "Railjack",
    "MT_RECOVERY": "Recovery",
    "MT_RESOURCE_THEFT": "MT_RESOURCE_THEFT",
    "MT_RETRIEVAL": "Hijack",
    "MT_SALVAGE": "Solar Rail Conflict",
    "MT_TAU_WAR": "The Perita Rebellion",
    "MT_TERRITORY": "Interception",
    "MT_VAULTS": "Netracells",
    "MT_VOID_CASCADE": "Void Cascade",
    "MT_ASSASSINATION": "Assassination",
    "MT_CAPTURE": "Capture",
    "MT_COUNTER_INTEL": "Deception",
    "MT_DEFENSE": "Defense",
    "MT_EXTERMINATION": "Extermination",
    "MT_INTEL": "Spy",
    "MT_MOBILE_DEFENSE": "Mobile Defense",
    "MT_RESCUE": "Rescue",
    "MT_SABOTAGE": "Sabotage",
    "MT_SURVIVAL": "Survival",
}
